const axios = require('axios');
const { Sequelize, MyDeckforBattle } = require('../models/Main');
const Main = require('../models/Main');
/*exports.index = (req, res) => {
  res.render('/');
  console.log('render index');
};
exports.deck_setting = (req, res) => {
  res.render('/DeckSetting');
  console.log('render DeckSetting');
};
exports.combat_demo = (req, res) => {
  res.render('/CombatDemo');
  console.log('render CombatDemo');
};*/
exports.battle_start = (req, res) => {
  console.log('req.body', req.body);
  //let characters = req.body;
  //res.render('battlePage', { characters });
};

exports.enemy_deck = (req, res) => {
  // 여기에서 적절한 방법으로 enemyDeckData를 가져와서 응답
  // 예시로 직접 데이터를 반환하면 다음과 같이 할 수 있습니다.
  const enemyDeckData = [
    {
      id: 7,
      charName: '오염된 전영중',
      HPcurrent: 99999,
      HPstat: 99999,
      physicResist: 4,
      magicResist: 3,
      attack: 11,
      speed: 5,
      accuracy: 0.9,
      evasion: 0.3,
      critical: 0.4,
      critDamageRate: 2.1,
      isMagic: false,
      isAdjutant: false,
      isEnemy: true,
      isSixMan: false,
      passiveSkill: '오염의 근원',
      activeSkillFirst: '어딜 가려고?',
      activeSkillSecond: '한심한 건 너잖아',
      ultSkill: '누가 계속 영웅하래!',
      buff: [
        {
          buffNumber: 0,
          buffType: '',
          buffFrom: '',
          buffStat: '',
          buffAmmount: 0,
          buffDuration: 0,
        },
      ],
      debuff: [
        {
          debuffNumber: 0,
          debuffType: '',
          debuffFrom: '',
          debuffStat: '',
          debuffAmmount: 0,
          debuffDuration: 0,
        },
      ],
      lovePointCurrent: 0,
      Position: 1,
      img: 'Boss_BBang_sd_1',
    },
    {
      id: 8,
      charName: '서은재',
      HPcurrent: 99999,
      HPstat: 99999,
      physicResist: 4,
      magicResist: 3,
      attack: 11,
      speed: 5,
      accuracy: 0.9,
      evasion: 0.3,
      critical: 0.4,
      critDamageRate: 2.1,
      isMagic: true,
      isAdjutant: false,
      isEnemy: true,
      isSixMan: false,
      passiveSkill: '응원단',
      activeSkillFirst: '우등생',
      activeSkillSecond: '비법노트',
      ultSkill: '사랑에 빠진 소녀',
      buff: [
        {
          buffNumber: 0,
          buffType: '',
          buffFrom: '',
          buffStat: '',
          buffAmmount: 0,
          buffDuration: 0,
        },
      ],
      debuff: [
        {
          debuffNumber: 0,
          debuffType: '',
          debuffFrom: '',
          debuffStat: '',
          debuffAmmount: 0,
          debuffDuration: 0,
        },
      ],
      lovePointCurrent: 0,
      Position: 4,
      img: 'seoeunjae_sd_1',
    },
    {
      id: 9,
      charName: '박병찬',
      HPcurrent: 99999,
      HPstat: 99999,
      physicResist: 4,
      magicResist: 3,
      attack: 11,
      speed: 5,
      accuracy: 0.9,
      evasion: 0.3,
      critical: 0.4,
      critDamageRate: 2.1,
      isMagic: false,
      isAdjutant: false,
      isEnemy: true,
      isSixMan: false,
      passiveSkill: '12분',
      activeSkillFirst: '제법인데?',
      activeSkillSecond: '걱정마세요',
      ultSkill: '죽여버릴거야...',
      buff: [
        {
          buffNumber: 0,
          buffType: '',
          buffFrom: '',
          buffStat: '',
          buffAmmount: 0,
          buffDuration: 0,
        },
      ],
      debuff: [
        {
          debuffNumber: 0,
          debuffType: '',
          debuffFrom: '',
          debuffStat: '',
          debuffAmmount: 0,
          debuffDuration: 0,
        },
      ],
      lovePointCurrent: 0,
      Position: 2,
      img: 'byeongchan_sd_1',
    },
    {
      id: 10,
      charName: '기상호',
      HPcurrent: 99999,
      HPstat: 99999,
      physicResist: 4,
      magicResist: 3,
      attack: 11,
      speed: 5,
      accuracy: 0.9,
      evasion: 0.3,
      critical: 0.4,
      critDamageRate: 2.1,
      isMagic: true,
      isAdjutant: false,
      isEnemy: true,
      isSixMan: false,
      passiveSkill: '언럭키',
      activeSkillFirst: '사륜안!',
      activeSkillSecond: '왼팔에 흑염룡이...',
      ultSkill: '에이스 브레이커',
      buff: [
        {
          buffNumber: 0,
          buffType: '',
          buffFrom: '',
          buffStat: '',
          buffAmmount: 0,
          buffDuration: 0,
        },
      ],
      debuff: [
        {
          debuffNumber: 0,
          debuffType: '',
          debuffFrom: '',
          debuffStat: '',
          debuffAmmount: 0,
          debuffDuration: 0,
        },
      ],
      lovePointCurrent: 0,
      Position: 3,
      img: 'sangho_sd_1',
    },
    {
      id: 11,
      charName: '성준수',
      HPcurrent: 99999,
      HPstat: 99999,
      physicResist: 4,
      magicResist: 3,
      attack: 11,
      speed: 5,
      accuracy: 0.9,
      evasion: 0.3,
      critical: 0.4,
      critDamageRate: 2.1,
      isMagic: false,
      isAdjutant: false,
      isEnemy: true,
      isSixMan: false,
      passiveSkill: '엘리트 출신',
      activeSkillFirst: '할 때는 한다',
      activeSkillSecond: '착각하지 마',
      ultSkill: '부숴버려',
      buff: [
        {
          buffNumber: 0,
          buffType: '',
          buffFrom: '',
          buffStat: '',
          buffAmmount: 0,
          buffDuration: 0,
        },
      ],
      debuff: [
        {
          debuffNumber: 0,
          debuffType: '',
          debuffFrom: '',
          debuffStat: '',
          debuffAmmount: 0,
          debuffDuration: 0,
        },
      ],
      lovePointCurrent: 0,
      Position: 5,
      img: 'junsu_sd_1',
    },
    {
      id: 12,
      charName: '김다은',
      HPcurrent: 99999,
      HPstat: 99999,
      physicResist: 4,
      magicResist: 3,
      attack: 11,
      speed: 5,
      accuracy: 0.9,
      evasion: 0.3,
      critical: 0.4,
      critDamageRate: 2.1,
      isMagic: false,
      isAdjutant: false,
      isEnemy: true,
      isSixMan: true,
      passiveSkill: '원래는 마법사가...',
      activeSkillFirst: '길을 찾고 싶어',
      activeSkillSecond: '마르세유 턴',
      ultSkill: '우직하게',
      buff: [
        {
          buffNumber: 0,
          buffType: '',
          buffFrom: '',
          buffStat: '',
          buffAmmount: 0,
          buffDuration: 0,
        },
      ],
      debuff: [
        {
          debuffNumber: 0,
          debuffType: '',
          debuffFrom: '',
          debuffStat: '',
          debuffAmmount: 0,
          debuffDuration: 0,
        },
      ],
      lovePointCurrent: 0,
      Position: 6,
      img: 'kimdaeun_sd_1',
    },
  ];
  res.json(enemyDeckData);
};
